apiVersion: apps/v1
kind: Deployment
metadata:
  name: attorney-ai-simplifier
spec:
  selector:
    matchLabels:
      app: attorney-ai-simplifier
  template:
    metadata:
      labels:
        app: attorney-ai-simplifier
    spec:
      containers:
      - name: attorney-ai-simplifier
        image: flavioheartnet/attorney-ai
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 500m
              memory: 25Mi